# kantin-k8s.yaml — GANTI SESUAI USERNAME DOCKER HUB KAMU
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-kantin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-api
        image: madeu30/praktikum1-backend-service:latest  # ← Ganti username
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:                                    # ← INI yang dimaksud inject via YAML
        - name: NAMA_MAHASISWA
          value: "Mahendra Devid Putra Anwar"            # ← Isi nama kamu
        - name: NIM_MAHASISWA
          value: "2407792"                    # ← Isi NIM kamu
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP   # ← Sesuai syarat soal (bukan LoadBalancer)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-kantin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-ui
        image: madeu30/praktikum1-frontend-service:latest  # ← Ganti username
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP   # ← Sesuai syarat soal